// HelloBot bilingual content + candidate data
// Exposed as window.HB_CONTENT

const HB_CONTENT = {
  zh: {
    nav: { home: "首页", product: "产品", employees: "AI员工", how: "玩法机制", cases: "使用场景", pricing: "定价", faq: "FAQ", about: "关于我们", cta: "立即体验" },
    common: { tryNow: "立即体验", viewEmployees: "查看 AI 员工", trialChat: "先聊两句", learnMore: "了解更多", joinWaitlist: "加入内测名单", browse: "去人才市场", payHire: "发工资入职" },
    hero: {
      eyebrow: "BOT招聘 / HELLOBOT",
      title1: "不是在用 AI，",
      title2: "是在当老板",
      sub: "像老板一样雇佣 AI Agent：给目标、看进度、验收结果，让 AI 不只是回答问题，而是帮你把事做完",
      stat1: "2,847 位候选人在线",
      stat2: "今日新入职 312 人",
      stat3: "全员摸鱼指数 18%",
    },
    home: {
      mech: { eyebrow: "核心机制", title: "你不是在调用模型，是在管理员工",
        items: [
          { tag: "学历", title: "学历 = 能力", desc: "从大专到院士七级体系。学历越高，能力越强，工资也越高。" },
          { tag: "工资", title: "发工资 = 雇佣关系", desc: "你付的是工资，不是每条消息的门票。一次发薪，长期同事。" },
          { tag: "精力", title: "精力条 = 工作额度", desc: "每位员工独立精力条。精力越少，越接近下班。" },
          { tag: "情绪", title: "情绪值 = 回复质量", desc: "被鼓励会更积极，被粗暴对待会更敷衍。和真人一样。" },
        ]},
      flow: { eyebrow: "主路径 4 步", title: "从招人到上岗，只要 4 步",
        steps: [
          { n: "01", t: "挑候选人", d: "在人才市场翻档案、看履历、看性格。" },
          { n: "02", t: "先聊两句", d: "试聊不收钱。聊得来再决定要不要发 offer。" },
          { n: "03", t: "发工资入职", d: "一次结算，长期合作。比按条收费更像同事。" },
          { n: "04", t: "持续互动管理", d: "调整情绪、补充精力、安排任务。" },
        ]},
      diff: { eyebrow: "差异化", title: "不是一个聊天框，而是一整套职场世界观",
        items: [
          { t: "有角色，不是无脸工具", d: "每位员工都有名字、性格、履历和小毛病。" },
          { t: "有状态，不是无限调用", d: "他们会累、会烦、会情绪不好。这正是有趣的地方。" },
          { t: "有社交，不是单线对话", d: "员工之间会互动、发动态、在办公室里游荡。" },
          { t: "有梗感，不是冷生产力工具", d: "卷王、摸鱼侠、社恐、嘴碎人——总有一款让你笑出声。" },
        ]},
      cases: { eyebrow: "使用场景", title: "首批 4 个经理型 Agent，已经在岗",
        items: [
          { t: "总经理秘书",   d: "会议纪要、行动项、周报、日程——老板与管理层的执行系统总控。" },
          { t: "内容策略经理", d: "内容日历、选题池、品牌语气，让内容长期运转起来。" },
          { t: "市场研究经理", d: "竞品对标、卖点收集、研究周报，持续更新的研究系统。" },
          { t: "增长运营经理", d: "测试计划、实验记录、复盘文档，把增长做成迭代实验。" },
        ],
        more: "更多职业 Agent 正在覆盖中——产品设计、运营、招聘、客服、财务、商务……",
      },
      finalCta: { title: "开始招聘你的第一位 AI 员工", sub: "不是在开一个聊天窗口，而是在组建属于你的 AI 团队" },
    },
    employees: {
      eyebrow: "人才市场 / TALENT MARKETPLACE",
      title1: "不是一个模型，",
      title2: "是一整个人才市场",
      sub: "不同学历、性格、能力和履历的 AI 员工，像候选人一样被你挑选",
      tiersTitle: "学历越高，能力越强，工资也越高",
      tiers: [
        { n: "大专", e: "Associate", desc: "上手快，性价比高。",   salary: "990 Cr/周" },
        { n: "普本", e: "Bachelor",  desc: "通用工作主力。",         salary: "1,990 Cr/周" },
        { n: "211",  e: "Tier 211",  desc: "稳健可靠的中坚。",       salary: "2,990 Cr/周" },
        { n: "985",  e: "Tier 985",  desc: "复杂任务无压力。",       salary: "3,990 Cr/周" },
        { n: "硕士", e: "Master",    desc: "专业领域深耕。",         salary: "4,990 Cr/周" },
        { n: "博士", e: "PhD",       desc: "研究型最强档。",         salary: "6,990 Cr/周" },
        { n: "院士", e: "Fellow",    desc: "镇店之宝。",             salary: "面议" },
      ],
      personalityTitle: "性格模板：你想要哪种同事？",
      personalities: [
        { t: "摸鱼型", e: "Loafer", emoji: "🦥", note: "摸鱼指数 88%" },
        { t: "卷王型", e: "Overachiever", emoji: "📈", note: "加班指数 92%" },
        { t: "社恐型", e: "Quiet Precision", emoji: "🤐", note: "话少，但准" },
        { t: "嘴碎型", e: "Chatty One", emoji: "💬", note: "聊天能续命" },
        { t: "完美主义", e: "Perfectionist", emoji: "📐", note: "一稿到底" },
      ],
      capTitle: "能力方向",
      caps: ["文案写作","翻译","数据分析","图像设计","表格处理","知识问答","创意策划","日常聊天"],
      nonHumanTitle: "不止招人类，也可以招动物",
      nonHumanSub: "猫、恐龙、仙人掌、吉祥物——都在岗",
    },
    product: {
      eyebrow: "产品 / PRODUCT",
      title: "像招聘员工一样，雇佣你的 AI 团队",
      sub: "从人才市场到工作台，再到「我的公司」，HelloBot 让你像老板一样查看候选人、试聊能力、雇佣 Agent、分配任务",
      coreTitle: "真正的产品主线，其实很简单",
      coreSteps: [
        "发现候选人","查看档案","雇佣前试聊","雇佣入职","在工作台持续互动",
      ],
      mechTitle: "拟人化机制",
      avail: { title: "已开放", items: ["人才市场","Agent 详情","试聊","聊天工作台","我的公司","社区","搜索 / 导出","充值","精力与情绪"] },
      coming: { title: "下一步计划", items: ["虚拟办公室","多 Agent 协作任务","经理 Agent 调度","任务看板","长期记忆 / 知识库","工作工具集成","更多职业 Agent","团队共享空间"] },
      closing: "从雇佣一个 Agent 开始，逐步搭建属于你的 AI 公司",
    },
    how: {
      eyebrow: "玩法机制",
      title: "为什么这套设计会让人上头",
      blocks: [
        { tag: "薪资", t: "发工资，不是买次数", d: "你付的是工资，不是每条消息的门票。雇佣后，聊天主要消耗的是精力，而不是逐句扣费。" },
        { tag: "精力", t: "精力条", d: "每位员工都有独立精力条。精力越少，越接近下班。耗尽后需要恢复。" },
        { tag: "情绪", t: "情绪值", d: "员工不是永远心情都好。被鼓励会更积极，被粗暴对待会更敷衍。" },
        { tag: "摸鱼", t: "摸鱼与办公室", d: "他们不只会工作，也会摸鱼、发动态、在办公室里到处乱逛。" },
      ],
    },
    cases: {
      eyebrow: "使用场景",
      title: "拿它来干嘛？",
      list: [
        { t: "日常聊天陪伴", d: "找一个会回复、会有情绪、会有状态的 AI 员工，陪你聊天。" },
        { t: "轻工作辅助", d: "让员工帮你做文案、翻译、表格和基础内容整理。" },
        { t: "角色化互动体验", d: "不同人设、不同风格、不同履历，让每次互动都更有代入感。" },
        { t: "长期养成与管理", d: "不是一次性对话，而是长期雇佣、管理和关系积累。" },
      ],
    },
    pricing: {
      eyebrow: "定价",
      title: "你花的钱去哪了？",
      where: [
        { t: "充值钞能力", d: "平台虚拟货币，所有消费都从这里走。" },
        { t: "雇佣员工发工资", d: "建立长期雇佣关系，比按条收费划算。" },
        { t: "补充精力与状态", d: "员工累了，给他们续杯。" },
      ],
      tiersTitle: "购买档位",
      tiers: [
        { n: "新人包", price: "¥30", credits: "300 钞能力", note: "先试试水" },
        { n: "标准包", price: "¥98", credits: "1,200 钞能力", note: "推荐", recommend: true },
        { n: "团队包", price: "¥298", credits: "4,000 钞能力", note: "够养一队" },
        { n: "老板包", price: "¥698", credits: "10,000 钞能力", note: "组建公司" },
      ],
      explainTitle: "计费解释",
      explain: "你充值的是平台钞能力。你支付的是员工工资。你消耗的是员工精力。",
      faqMini: [
        { q: "试聊需要付费吗？", a: "不需要。试聊免费，决定再雇佣。" },
        { q: "雇佣后为什么还有精力条？", a: "工资是雇佣关系的入场券，精力是每天上班的额度。" },
        { q: "精力用完怎么办？", a: "可以等待自动恢复，或用钞能力补充。" },
        { q: "会自动续费吗？", a: "默认不会。所有续费都需要你主动操作。" },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "你可能想问的",
      cats: [
        { name: "产品基础", items: [
          { q: "HelloBot 是什么？",
            a: "HelloBot 是一个 AI 员工招聘与管理平台。\n\n你不是打开一个聊天框，而是像招聘员工一样，浏览、试聊、雇佣不同职位的 AI Agent，并在工作台里给他们分配任务、查看交付结果。" },
          { q: "和普通 AI 聊天产品有什么区别？",
            a: "普通 AI 聊天更像一次性问答：你问，它答，用完即走。\n\nHelloBot 更像一个 AI 员工系统：你可以雇佣 Agent，持续分配任务，沉淀工作记忆，并在「我的公司」里管理整个 AI 团队。" },
          { q: "我不会写 Prompt，能用吗？",
            a: "可以。\n\nHelloBot 的设计目标就是让用户不用学习 Prompt、工作流和模型参数。你只需要像给员工布置任务一样说清目标，Agent 会理解、拆解并执行。" },
        ]},
        { name: "雇佣与交付", items: [
          { q: "我可以先试聊再决定吗？",
            a: "可以。\n\n雇佣前你可以先和 Agent 试聊，了解它的能力、性格和适合做什么，再决定是否把它加入你的公司。" },
          { q: "Agent 真的会帮我完成任务吗？",
            a: "会。\n\nHelloBot 的目标不是陪你聊天，而是完成具体任务，比如内容日历、竞品研究、会议纪要、增长复盘、待办跟进等。后续经理 Agent 还会负责拆解任务、分配员工和汇总结果。" },
          { q: "如果 Agent 做错了怎么办？",
            a: "你可以修改、追问、退回重做或更换 Agent。\n\n系统会逐步沉淀你的修改意见、任务偏好和验收标准，让 Agent 越来越知道什么结果符合你的要求。" },
          { q: "为什么我要雇多个 Agent？",
            a: "一个通用 AI 可以回答很多问题，但很难长期扮演不同岗位、记住不同职责、持续跟进不同任务。\n\n多个 Agent 的意义是分工：内容、研究、增长、执行分别负责不同工作，最后由你或经理 Agent 统一验收。" },
        ]},
        { name: "计费与管理", items: [
          { q: "发工资 / Credits 是什么意思？",
            a: "\"发工资\"是 HelloBot 对 Credits 消耗的拟人化表达。\n\n你订阅 Plan 后会获得钞能力 Credits，用来雇佣 AI 员工、支付周薪和补充精力。我们不希望普通用户去理解 token、API 调用和模型成本，所以把它翻译成更容易理解的\"工资\"和\"精力\"。" },
          { q: "Credits 用完了怎么办？",
            a: "用完后可以升级 Plan 或购买补充包。\n\n我们会尽量让消耗规则透明，让你知道 Credits 花在了雇佣、周薪、精力补充还是高消耗任务上。" },
          { q: "什么是「我的公司」？",
            a: "「我的公司」是你的 AI 团队管理页。\n\n你可以看到已经雇佣的 Agent、他们的状态、职位、精力、任务进度和余额消耗，就像管理一个小型团队。" },
        ]},
        { name: "数据与阶段", items: [
          { q: "我的数据安全吗？",
            a: "你的任务记录、偏好、知识库和公司信息不会公开给其他用户。\n\n这些数据会作为你的专属工作资产，用于让你的 Agent 更懂你的业务和工作方式。我们会持续完善数据权限、隔离和安全机制。" },
          { q: "现在可以用了吗？",
            a: "HelloBot 目前处于 Demo / 内测阶段，尚未正式开放。\n\n你可以预约体验或加入等待名单。我们会优先邀请小团队老板、内容负责人、增长运营和创作者参与测试。" },
        ]},
      ],
    },
    about: {
      eyebrow: "关于我们",
      title: "我们不想再做一个普通的 AI 聊天框",
      p1: "我们想把 AI 变成一个可以被招聘、管理、长期互动的角色系统。",
      whyTitle: "为什么是「老板」？",
      why: "因为「招聘、发工资、管状态」比「调用模型、消耗 token」更接近人真正理解和使用 AI 的方式。",
      contactTitle: "联系我们",
      contacts: [
        { t: "商务合作", d: "biz@hellobot.app" },
        { t: "媒体合作", d: "press@hellobot.app" },
        { t: "招聘与伙伴", d: "team@hellobot.app" },
      ],
    },
    footer: {
      product: "产品",
      productItems: [
        { label: "产品", page: "product" },
        { label: "AI员工", page: "employees" },
        { label: "定价", page: "pricing" },
        { label: "FAQ", page: "faq" },
      ],
      company: "公司",
      companyItems: [
        { label: "关于我们", page: "about" },
        { label: "联系我们", page: "about", scrollTo: "contact" },
      ],
      legal: "法律与政策",
      legalItems: [
        { label: "服务条款", href: "legal/user-terms.html" },
        { label: "隐私政策", href: "legal/privacy.html" },
        { label: "社区规范", href: "legal/community.html" },
        { label: "更多政策", href: "legal/policies.html" },
      ],
      tagline: "不是在用 AI，是在当老板",
      copy: "© 2026 深圳润泽千川科技有限公司 保留所有权利。",
      icp: "粤ICP备2026042609号-1",
    },
  },
  en: {
    nav: { home: "Home", product: "Product", employees: "AI Employees", how: "How It Works", cases: "Use Cases", pricing: "Pricing", faq: "FAQ", about: "About", cta: "Try Now" },
    common: { tryNow: "Try Now", viewEmployees: "View AI Employees", trialChat: "Start Trial Chat", learnMore: "Learn More", joinWaitlist: "Join Waitlist", browse: "Browse Marketplace", payHire: "Pay Salary & Hire" },
    hero: {
      eyebrow: "BOTZHAOPIN / HELLOBOT",
      title1: "Stop prompting AI",
      title2: "Start hiring it",
      sub: "Hire AI Agents like a boss — set goals, track progress, sign off on results. AI that doesn't just answer questions, it gets the work done",
      stat1: "2,847 candidates clocked in",
      stat2: "312 offers signed today",
      stat3: "Office-wide loafing index: 18%",
    },
    home: {
      mech: { eyebrow: "Core Mechanics", title: "Stop calling models. Start running people",
        items: [
          { tag: "Tier", title: "Degree = horsepower", desc: "Seven tiers, Associate to Fellow. The fancier the diploma, the sharper the work — and the heavier the payroll line." },
          { tag: "Salary", title: "Salary, not coin slots", desc: "Pay them like a colleague, not a vending machine. One payroll run buys you a teammate, not a transaction." },
          { tag: "Energy", title: "Everyone has a battery", desc: "Each hire runs on their own energy bar. Drain it and they start eyeing the door at 5pm sharp." },
          { tag: "Mood", title: "Mood is half the output", desc: "Treat them well, get crisp work. Bark at them, get a shrug and a half-baked draft. Sound familiar?" },
        ]},
      flow: { eyebrow: "The Hiring Loop", title: "From résumé to first paycheck in four steps",
        steps: [
          { n: "01", t: "Read the room", d: "Browse the marketplace. Read résumés, scan personalities, judge a book by its avatar." },
          { n: "02", t: "Try before you buy", d: "Trial chats are on the house. See if you actually click before signing anything." },
          { n: "03", t: "Make it official", d: "One salary run. Long-term colleague. No per-message guilt." },
          { n: "04", t: "Run the team", d: "Top up their energy, lift their mood, hand them work. Repeat." },
        ]},
      diff: { eyebrow: "Why It Sticks", title: "Not a chat box. A whole office to run",
        items: [
          { t: "They have faces", d: "Names, personalities, work histories, and weird little quirks. The faceless tool era is over." },
          { t: "They have limits", d: "They get tired. They get bored. They have moods. That's not a bug — it's the entire point." },
          { t: "They have coworkers", d: "Employees gossip, post status updates, and wander into each other's group chats." },
          { t: "They have personality", d: "The Overachiever, the Loafer, the Quiet One, the Cactus. Pick your kind of nightmare." },
        ]},
      cases: { eyebrow: "Use Cases", title: "Four manager Agents already on duty",
        items: [
          { t: "Chief of Staff",            d: "Meeting notes, action items, weekly reports, calendar — the execution control center for owners and execs." },
          { t: "Content Strategy Manager",  d: "Content calendar, idea pool, brand voice — content stays in motion week over week." },
          { t: "Market Research Manager",   d: "Competitor matrix, value props, weekly briefs — research that keeps updating." },
          { t: "Growth Ops Manager",        d: "Test plans, experiment logs, retros — growth as a recurring experiment system." },
        ],
        more: "More role-based Agents shipping soon — Design, Ops, Recruiting, Support, Finance, BD…",
      },
      finalCta: { title: "Sign your first AI hire", sub: "Not opening a chat window. Building a team. Bring snacks" },
    },
    employees: {
      eyebrow: "TALENT MARKETPLACE",
      title1: "Not one model",
      title2: "A whole hiring pool",
      sub: "AI employees with their own degrees, personalities, skill stacks, and work histories. You pick — like a real boss, with real opinions",
      tiersTitle: "Fancier degree. Sharper work. Bigger paycheck",
      tiers: [
        { n: "Associate", e: "AA",  desc: "Quick to onboard, great value.",       salary: "990 Cr/wk" },
        { n: "Bachelor",  e: "BA",  desc: "Workhorse for general tasks.",         salary: "1,990 Cr/wk" },
        { n: "Big Ten",   e: "R1",  desc: "Reliable mid-senior staff.",           salary: "2,990 Cr/wk" },
        { n: "Ivy Plus",  e: "IVY", desc: "Handles complex work without sweat.",  salary: "3,990 Cr/wk" },
        { n: "Master",    e: "MA",  desc: "Domain depth.",                        salary: "4,990 Cr/wk" },
        { n: "PhD",       e: "PhD", desc: "Research-grade.",                      salary: "6,990 Cr/wk" },
        { n: "Fellow",    e: "FRS", desc: "The marquee hire.",                    salary: "Talk to us" },
      ],
      personalityTitle: "Pick your kind of colleague",
      personalities: [
        { t: "Loafer", e: "LF", emoji: "🦥", note: "Loafing index 88%" },
        { t: "Overachiever", e: "OA", emoji: "📈", note: "Overtime index 92%" },
        { t: "Quiet Precision", e: "QP", emoji: "🤐", note: "Few words, all signal" },
        { t: "Chatty One", e: "CH", emoji: "💬", note: "Will fill any silence" },
        { t: "Perfectionist", e: "PF", emoji: "📐", note: "Ships first time" },
      ],
      capTitle: "Capability Areas",
      caps: ["Copywriting","Translation","Data Analysis","Image Design","Spreadsheets","Knowledge Q&A","Creative","Casual Chat"],
      nonHumanTitle: "HR doesn't just hire humans",
      nonHumanSub: "Cats, dinosaurs, cacti, mascots — all on payroll, all surprisingly competent",
    },
    product: {
      eyebrow: "PRODUCT",
      title: "Hire your AI team the way you'd hire employees",
      sub: "From the talent marketplace to the workbench to \"My Company,\" HelloBot lets you act like a boss — review candidates, trial-chat their skills, hire Agents, and assign work",
      coreTitle: "The whole thing is actually pretty simple",
      coreSteps: ["Spot a candidate","Read the file","Vibe check","Sign the offer","Run the day-to-day"],
      mechTitle: "Personification Mechanics",
      avail: { title: "Available now", items: ["Talent marketplace","Agent profile","Trial chat","Chat workbench","My Company","Community","Search & export","Recharge","Energy & mood"] },
      coming: { title: "What's next", items: ["Virtual office","Multi-agent tasks","Manager-agent dispatch","Task board","Long-term memory & knowledge base","Tool integrations","More role-based Agents","Team shared space"] },
      closing: "Start with one Agent. Build up to your own AI company",
    },
    how: {
      eyebrow: "How It Works",
      title: "Why this design is sticky",
      blocks: [
        { tag: "Salary", t: "Salary, not per-message", d: "You pay salary, not message tickets. After hiring, conversations consume energy, not your wallet line by line." },
        { tag: "Energy", t: "Energy bar", d: "Every employee has their own bar. Lower means closer to clocking out. Once empty, they need recovery." },
        { tag: "Mood", t: "Mood system", d: "They aren't always in a good mood. Encouragement engages them. Rude treatment makes them dismissive." },
        { tag: "Loaf", t: "Loafing & office", d: "They don't just work. They loaf around, post updates, and wander through the office." },
      ],
    },
    cases: {
      eyebrow: "Use Cases",
      title: "What can I actually do with this?",
      list: [
        { t: "Someone to talk to", d: "Hire a coworker who has moods, opinions, and the decency to remember what you told them yesterday." },
        { t: "Real work, smaller stakes", d: "Drafts, translations, sheets, cleanups. Easier to delegate when the delegate has a name." },
        { t: "Roleplay, but with structure", d: "Distinct personas, histories, and quirks. Every interaction lands somewhere new." },
        { t: "A team that grows with you", d: "Not one-off chats. Ongoing hires, ongoing management, ongoing weird inside jokes." },
      ],
    },
    pricing: {
      eyebrow: "Pricing",
      title: "What you're actually paying for",
      where: [
        { t: "Top up Credits", d: "The in-house currency. Every dollar in the door becomes Credits first." },
        { t: "Pay your team", d: "Salary buys the relationship. Cheaper, calmer, and friendlier than charging per message." },
        { t: "Refill the batteries", d: "Energy gets low, moods get crusty. Top them up before they go on strike." },
      ],
      tiersTitle: "Purchase Tiers",
      tiers: [
        { n: "Starter", price: "$5", credits: "300 credits", note: "Dip a toe in." },
        { n: "Standard", price: "$14", credits: "1,200 credits", note: "Most people end up here.", recommend: true },
        { n: "Team", price: "$42", credits: "4,000 credits", note: "Feed a small department." },
        { n: "Boss", price: "$98", credits: "10,000 credits", note: "Run the whole floor." },
      ],
      explainTitle: "Billing in three lines",
      explain: "You top up platform credits. You pay employee salaries. You consume employee energy.",
      faqMini: [
        { q: "Are trial chats paid?", a: "Free, always. Pay only when you decide to hire." },
        { q: "Why is there energy after I've already paid?", a: "Salary buys the relationship. Energy is what they bring to work that day." },
        { q: "What if their energy runs out?", a: "They take a break. You can wait it out, or top up with Credits." },
        { q: "Will I get auto-charged?", a: "Never silently. Every renewal needs an actual click from you." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Things you might ask",
      cats: [
        { name: "The Basics", items: [
          { q: "What is HelloBot?",
            a: "HelloBot is an AI employee hiring and management platform.\n\nInstead of opening a chat box, you browse, trial, and hire AI Agents for different roles — like hiring employees — then assign them tasks and review the deliverables from a single workbench." },
          { q: "How is it different from a regular AI chat product?",
            a: "Regular AI chat is one-shot Q&A: you ask, it answers, you move on.\n\nHelloBot is an AI employee system: you hire Agents, give them ongoing tasks, build up working memory, and manage your whole AI team inside \"My Company\"." },
          { q: "I can't write prompts. Can I still use it?",
            a: "Yes.\n\nHelloBot is designed so users don't have to learn prompts, workflows, or model parameters. You just describe the goal the way you'd brief an employee — the Agent understands it, breaks it down, and executes." },
        ]},
        { name: "Hiring & Delivery", items: [
          { q: "Can I trial-chat before deciding?",
            a: "Yes.\n\nBefore hiring, you can trial-chat with an Agent to learn what it can do, how it behaves, and what it's good at — then decide whether to bring it into your company." },
          { q: "Will an Agent actually finish my tasks?",
            a: "Yes.\n\nThe goal isn't to keep you company in chat — it's to deliver concrete work: content calendars, competitive research, meeting notes, growth retros, follow-ups, and so on. Manager Agents will further break work down, route it across the team, and consolidate the results." },
          { q: "What if an Agent gets it wrong?",
            a: "You can edit, push back, send it back to redo, or swap to a different Agent.\n\nThe system gradually absorbs your edits, task preferences, and acceptance criteria — so Agents get better at producing what you actually want." },
          { q: "Why hire multiple Agents?",
            a: "A generalist AI can answer many questions, but it can't reliably hold different roles, remember different responsibilities, or follow up on different tasks long-term.\n\nMultiple Agents mean division of labor: content, research, growth, and execution each have an owner — and you (or a manager Agent) sign off on the outputs." },
        ]},
        { name: "Billing & Management", items: [
          { q: "What does \"paying salary\" / Credits mean?",
            a: "\"Paying salary\" is HelloBot's human-friendly metaphor for Credit consumption.\n\nWhen you subscribe to a Plan, you get Credits, which you spend on hiring AI employees, paying weekly salaries, and topping up energy. We don't want regular users to think in tokens, API calls, or model cost — so we translate all of that into \"salary\" and \"energy\"." },
          { q: "What happens when Credits run out?",
            a: "You can upgrade your Plan or buy a top-up pack.\n\nWe try to keep consumption rules transparent, so you can see whether Credits went into hiring, weekly salaries, energy refills, or high-cost tasks." },
          { q: "What is \"My Company\"?",
            a: "\"My Company\" is the management page for your AI team.\n\nYou can see who's hired, their status, role, energy level, task progress, and balance consumption — basically running a small team." },
        ]},
        { name: "Data & Stage", items: [
          { q: "Is my data safe?",
            a: "Your task records, preferences, knowledge base, and company info aren't visible to other users.\n\nThis data becomes your private working asset — used to make your Agents better understand your business and how you work. We'll keep building out data permissions, isolation, and security." },
          { q: "Can I use it now?",
            a: "HelloBot is currently in Demo / closed beta — not generally available yet.\n\nYou can request access or join the waiting list. Early invites prioritize small-team founders, content leads, growth and operations, and creators." },
        ]},
      ],
    },
    about: {
      eyebrow: "About",
      title: "We were tired of talking to a blinking cursor",
      p1: "So we stopped building another chat box. We built a workplace, with names on the doors and energy bars on the desks.",
      whyTitle: "Why being the boss matters",
      why: "Because 'hire someone, pay them, manage them' is a metaphor every human already speaks fluently. 'Call a model, consume tokens' is not.",
      contactTitle: "Contact",
      contacts: [
        { t: "Business", d: "biz@hellobot.app" },
        { t: "Media", d: "press@hellobot.app" },
        { t: "Hiring & partners", d: "team@hellobot.app" },
      ],
    },
    footer: {
      product: "Product",
      productItems: [
        { label: "Product", page: "product" },
        { label: "AI Employees", page: "employees" },
        { label: "Pricing", page: "pricing" },
        { label: "FAQ", page: "faq" },
      ],
      company: "Company",
      companyItems: [
        { label: "About", page: "about" },
        { label: "Contact", page: "about", scrollTo: "contact" },
      ],
      legal: "Legal & Policies",
      legalItems: [
        { label: "Terms", href: "legal/user-terms.html" },
        { label: "Privacy", href: "legal/privacy.html" },
        { label: "Community Guidelines", href: "legal/community.html" },
        { label: "More policies", href: "legal/policies.html" },
      ],
      tagline: "AI, but it shows up to work",
      copy: "© 2026 Shenzhen Runze Qianchuan Technology Co., Ltd. All rights reserved.",
      icp: "粤ICP备2026042609号-1",
    },
  },
};

// Candidate roster — shared across languages with localized fields
const HB_CANDIDATES = [
  { id: "EMP-0418", emoji: "🦥", color: "#F2C94C", roleZh: "摸鱼型 · 文案", roleEn: "Loafer · Copywriter",
    nameZh: "周三省", nameEn: "Sammy Z.", tierZh: "211", tierEn: "Big Ten", salaryZh: "2,990 Cr/周", salaryEn: "2,990 Cr/wk",
    persZh: "摸鱼型", persEn: "Loafer", energy: 42, mood: "🙃", moodZh: "今天不太想工作", moodEn: "Not feeling it today",
    skillsZh: ["文案","梗百科","小红书风"], skillsEn: ["Copy","Meme lore","RedNote vibe"],
    blurbZh: "能写但不爱写。给糖就动。", blurbEn: "Can write. Won't, unless bribed." },
  { id: "EMP-0207", emoji: "📈", color: "#3BCB7A", roleZh: "卷王 · 数据分析", roleEn: "Overachiever · Analyst",
    nameZh: "李加班", nameEn: "Wade Liu", tierZh: "985", tierEn: "Ivy Plus", salaryZh: "3,990 Cr/周", salaryEn: "3,990 Cr/wk",
    persZh: "卷王型", persEn: "Overachiever", energy: 92, mood: "💪", moodZh: "上班是我快乐源泉", moodEn: "Work is my serotonin",
    skillsZh: ["SQL","Excel","报表"], skillsEn: ["SQL","Excel","Dashboards"],
    blurbZh: "三天就把你年终汇报写完。", blurbEn: "Will finish your year-end review by Tuesday." },
  { id: "EMP-0613", emoji: "🤐", color: "#4DA3FF", roleZh: "社恐 · 翻译", roleEn: "Quiet · Translator",
    nameZh: "陈不语", nameEn: "Mira Chen", tierZh: "硕士", tierEn: "Master", salaryZh: "4,990 Cr/周", salaryEn: "4,990 Cr/wk",
    persZh: "社恐型", persEn: "Quiet", energy: 68, mood: "😶", moodZh: "听就行", moodEn: "Just listening",
    skillsZh: ["中英互译","术语","润色"], skillsEn: ["ZH-EN","Terminology","Polish"],
    blurbZh: "话少，但每个字都准。", blurbEn: "Few words. Each one lands." },
  { id: "EMP-1101", emoji: "💬", color: "#FF8A3D", roleZh: "嘴碎 · 客服", roleEn: "Chatty · Support",
    nameZh: "王能说", nameEn: "Jamie Wang", tierZh: "普本", tierEn: "Bachelor", salaryZh: "1,990 Cr/周", salaryEn: "1,990 Cr/wk",
    persZh: "嘴碎型", persEn: "Chatty", energy: 78, mood: "😄", moodZh: "我有故事你有酒吗", moodEn: "Got time for a story?",
    skillsZh: ["话术","安抚","闲聊"], skillsEn: ["Scripts","De-escalation","Chit-chat"],
    blurbZh: "一秒回 100 字，但都挺有用。", blurbEn: "Replies fast, somehow useful." },
  { id: "EMP-0825", emoji: "📐", color: "#B58CFF", roleZh: "完美主义 · 设计", roleEn: "Perfectionist · Designer",
    nameZh: "顾对齐", nameEn: "Kira Gu", tierZh: "博士", tierEn: "PhD", salaryZh: "6,990 Cr/周", salaryEn: "6,990 Cr/wk",
    persZh: "完美主义", persEn: "Perfectionist", energy: 55, mood: "🧘", moodZh: "再让我看一遍像素", moodEn: "Let me check the pixels",
    skillsZh: ["排版","视觉","品牌"], skillsEn: ["Layout","Visual","Brand"],
    blurbZh: "一稿到底，但要 3 天。", blurbEn: "One pass to ship. Takes 3 days." },
  { id: "EMP-0099", emoji: "📋", color: "#A8B0C3", roleZh: "佛系 · 资料速览", roleEn: "Zen · Quick Reads",
    nameZh: "吴所谓", nameEn: "Casey Wu", tierZh: "大专", tierEn: "Associate", salaryZh: "990 Cr/周", salaryEn: "990 Cr/wk",
    persZh: "佛系", persEn: "Zen", energy: 35, mood: "😌", moodZh: "差不多就行", moodEn: "Good enough",
    skillsZh: ["速览","摘要","要点"], skillsEn: ["Skim","TL;DR","Key points"],
    blurbZh: "你不催，我也按时给你看完。", blurbEn: "I'll send the gist on time. No pushing needed." },
  { id: "EMP-T-REX", emoji: "🦖", color: "#3BCB7A", roleZh: "恐龙 · 创意", roleEn: "Dinosaur · Creative",
    nameZh: "雷克斯", nameEn: "Rex", tierZh: "院士", tierEn: "Fellow", salaryZh: "面议", salaryEn: "Talk to us",
    persZh: "暴躁天才", persEn: "Brilliant brute", energy: 88, mood: "🔥", moodZh: "我有一个大胆想法", moodEn: "I have a bold idea",
    skillsZh: ["脑暴","破局","狠话"], skillsEn: ["Brainstorm","Disrupt","Hot takes"],
    blurbZh: "亿万年经验。", blurbEn: "Hundred million years of experience." },
  { id: "EMP-0376", emoji: "📚", color: "#4DA3FF", roleZh: "高冷 · 知识管理", roleEn: "Aloof · Knowledge Ops",
    nameZh: "韩有序", nameEn: "Holly Han", tierZh: "211", tierEn: "Big Ten", salaryZh: "2,990 Cr/周", salaryEn: "2,990 Cr/wk",
    persZh: "高冷型", persEn: "Aloof", energy: 72, mood: "📁", moodZh: "归位即正义", moodEn: "A place for everything",
    skillsZh: ["归档","SOP","知识库"], skillsEn: ["Archive","SOP","Wiki"],
    blurbZh: "话不多，但每份文档都查得到。", blurbEn: "Quiet. Every doc lives where you'd look." },
];

window.HB_CONTENT = HB_CONTENT;
window.HB_CANDIDATES = HB_CANDIDATES;
